package service

import (
	"context"
	"fmt"

	"github.com/edgebase/platform/control-plane/internal/model"
	"github.com/edgebase/platform/control-plane/internal/mqtt"
	"github.com/edgebase/platform/control-plane/internal/repository"
	"github.com/google/uuid"
)

type VMService interface {
	CreateVM(ctx context.Context, nodeID uuid.UUID, spec model.VM) (*model.VM, error)
	GetVM(ctx context.Context, vmID uuid.UUID) (*model.VM, error)
	ListVMs(ctx context.Context, nodeID uuid.UUID) ([]model.VM, error)
	DeleteVM(ctx context.Context, vmID uuid.UUID) error
	StartVM(ctx context.Context, vmID uuid.UUID) error
	StopVM(ctx context.Context, vmID uuid.UUID) error
}

type vmService struct {
	repo       repository.VMRepository
	mqttClient *mqtt.Client
}

func NewVMService(repo repository.VMRepository, mqttClient *mqtt.Client) VMService {
	return &vmService{
		repo:       repo,
		mqttClient: mqttClient,
	}
}

func (s *vmService) CreateVM(ctx context.Context, nodeID uuid.UUID, spec model.VM) (*model.VM, error) {
	spec.NodeID = nodeID
	spec.Status = "created" // Initial status
	// spec.ID is generated by DB default if empty, but we might want to return it.
	// Gorm usually updates the struct.
	
	if err := s.repo.Create(ctx, &spec); err != nil {
		return nil, err
	}

	// Notify edge node via MQTT if available
	if s.mqttClient != nil {
		topic := fmt.Sprintf("nodes/%s/vms/create", nodeID)
		_ = s.mqttClient.Publish(topic, spec)
	}

	return &spec, nil
}

func (s *vmService) GetVM(ctx context.Context, vmID uuid.UUID) (*model.VM, error) {
	return s.repo.GetByID(ctx, vmID)
}

func (s *vmService) ListVMs(ctx context.Context, nodeID uuid.UUID) ([]model.VM, error) {
	return s.repo.ListByNodeID(ctx, nodeID)
}

func (s *vmService) DeleteVM(ctx context.Context, vmID uuid.UUID) error {
	vm, err := s.repo.GetByID(ctx, vmID)
	if err != nil {
		return err
	}
	
	if err := s.repo.Delete(ctx, vmID); err != nil {
		return err
	}

	if s.mqttClient != nil {
		topic := fmt.Sprintf("nodes/%s/vms/delete", vm.NodeID)
		payload := map[string]string{"id": vmID.String()}
		_ = s.mqttClient.Publish(topic, payload)
	}
	return nil
}

func (s *vmService) StartVM(ctx context.Context, vmID uuid.UUID) error {
	vm, err := s.repo.GetByID(ctx, vmID)
	if err != nil {
		return err
	}
	
	vm.Status = "running" // Desired state
	if err := s.repo.Update(ctx, vm); err != nil {
		return err
	}

	if s.mqttClient != nil {
		topic := fmt.Sprintf("nodes/%s/vms/start", vm.NodeID)
		payload := map[string]string{"id": vmID.String()}
		_ = s.mqttClient.Publish(topic, payload)
	}
	return nil
}

func (s *vmService) StopVM(ctx context.Context, vmID uuid.UUID) error {
	vm, err := s.repo.GetByID(ctx, vmID)
	if err != nil {
		return err
	}

	vm.Status = "stopped" // Desired state
	if err := s.repo.Update(ctx, vm); err != nil {
		return err
	}

	if s.mqttClient != nil {
		topic := fmt.Sprintf("nodes/%s/vms/stop", vm.NodeID)
		payload := map[string]string{"id": vmID.String()}
		_ = s.mqttClient.Publish(topic, payload)
	}
	return nil
}
